### ISSUE TITLE
redux instead of reflux

### ISSUE THREAD

**Issue by fizerkhan** [Syncano/syncano-dashboard#269]
Is there any plan to move from reflux to redux?

**Comment by wpasinski** [comment]
Hi @fizerkhan! Thank you for asking your question.

If you are interested in the future of Syncano, please see out blog post [We Open-Sourced Our Dashboard and Here’s Why](https://www.syncano.io/blog/open-source-dashboard/). You can find there that we are going to use a different state management library. Unfortunately I cannot provide any more information right now.

**Comment by fizerkhan** [comment]
@wpasinski Thanks for your update.

**Comment by Tiendq** [comment]
@wpasinski I read your mentioned blog post, actually it is where I was directed to from a google search about open source. It was 3 months ago and do you still prefer MobX to redux? :)
